'use client';

import { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { ProductCard } from '@/components/product-card';
import { StoreFooter } from '@/components/store-footer';
import { StoreHeader } from '@/components/store-header';
import { useStore } from '@/components/store-provider';
import { currency, products, type Product } from '@/lib/catalog';

export function ProductDetail({ product }: { product: Product }) {
  const [zoomOpen, setZoomOpen] = useState(false);
  const { addToCart, favorites, toggleFavorite } = useStore();
  const related = products.filter((item) => item.categorySlug === product.categorySlug && item.id !== product.id).slice(0, 4);
  const saved = favorites.includes(product.id);
  return <main><StoreHeader /><div className="breadcrumbs section-shell"><a href="/">Inicio</a><span>›</span><a href={`/categoria/${product.categorySlug}`}>{product.category}</a><span>›</span><strong>{product.brand}</strong></div><section className="product-detail section-shell"><div className="detail-gallery"><button className="zoom-trigger" onClick={() => setZoomOpen(true)} aria-label={`Ampliar imagen de ${product.name}`}><span className="discount">-{product.discount}%</span><img src={product.image} alt={product.name} /><span className="zoom-hint">⌕ tocar para ampliar</span></button><p>Seleccioná la imagen para verla en tamaño completo.</p></div><div className="detail-info">{product.tag && <span className="detail-tag">{product.tag}</span>}<span className="product-brand">{product.brand}</span><h1>{product.name}</h1><div className="rating detail-rating" aria-label="Calificación 4.8 de 5">★★★★★ <span>4.8 · 126 opiniones</span></div><p className="detail-description">{product.description}</p><div className="detail-price"><del>{currency.format(product.oldPrice)}</del><strong>{currency.format(product.price)}</strong><span>Ahorrás {currency.format(product.oldPrice - product.price)}</span></div><p className="detail-installments">6 cuotas sin recargo de <b>{currency.format(Math.ceil(product.price / 6))}</b></p><div className="detail-actions"><button className="primary-action" onClick={() => addToCart(product)}>agregar a mi bolsa</button><button className={`favorite-action ${saved ? 'saved' : ''}`} aria-label={saved ? 'Quitar de favoritos' : 'Agregar a favoritos'} onClick={() => toggleFavorite(product.id)}>{saved ? '♥' : '♡'}</button></div><div className="detail-delivery"><span>◇</span><div><strong>Envíos a todo Uruguay</strong><p>Envío gratis desde {currency.format(2500)}</p></div></div></div></section><section className="product-content section-shell"><article><span>beneficios</span><h2>Por qué te va a encantar</h2><ul>{product.benefits.map((benefit) => <li key={benefit}>✓ {benefit}</li>)}</ul></article><article><span>modo de uso</span><h2>Sumalo a tu ritual</h2><p>{product.usage}</p></article></section>{related.length > 0 && <section className="products-section section-shell related-products"><div className="section-heading"><div><p>también te puede gustar</p><h2>Completá tu ritual</h2></div></div><div className="product-grid">{related.map((item) => <ProductCard product={item} key={item.id} />)}</div></section>}<StoreFooter /><Dialog open={zoomOpen} onOpenChange={setZoomOpen}><DialogContent className="zoom-dialog" aria-describedby="zoom-description"><DialogTitle className="zoom-title">{product.name}</DialogTitle><DialogDescription id="zoom-description" className="zoom-description">Vista ampliada del producto</DialogDescription><img src={product.image} alt={`Vista ampliada de ${product.name}`} /></DialogContent></Dialog></main>;
}
